// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQdMCRRrl91JSt2cSNujqt1V5_aHLO-8E',
    appId: '1:87463974818:web:075ac32caa6ceee40544fb',
    messagingSenderId: '87463974818',
    projectId: 'eaio-9e3cb',
    authDomain: 'eaio-9e3cb.firebaseapp.com',
    storageBucket: 'eaio-9e3cb.appspot.com',
    measurementId: 'G-TMCJEE271H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAHabm9c4Fv8nsKCby6SrpcwaRB_SkTk4',
    appId: '1:87463974818:android:a989c8475468fd960544fb',
    messagingSenderId: '87463974818',
    projectId: 'eaio-9e3cb',
    storageBucket: 'eaio-9e3cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkwD3JiditL1vzbkzvzQlwW8GCc2r-2Ng',
    appId: '1:87463974818:ios:acf99e9610f1f9c80544fb',
    messagingSenderId: '87463974818',
    projectId: 'eaio-9e3cb',
    storageBucket: 'eaio-9e3cb.appspot.com',
    iosBundleId: 'com.example.eaisoft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkwD3JiditL1vzbkzvzQlwW8GCc2r-2Ng',
    appId: '1:87463974818:ios:acf99e9610f1f9c80544fb',
    messagingSenderId: '87463974818',
    projectId: 'eaio-9e3cb',
    storageBucket: 'eaio-9e3cb.appspot.com',
    iosBundleId: 'com.example.eaisoft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQdMCRRrl91JSt2cSNujqt1V5_aHLO-8E',
    appId: '1:87463974818:web:cd5546d0b30fb8770544fb',
    messagingSenderId: '87463974818',
    projectId: 'eaio-9e3cb',
    authDomain: 'eaio-9e3cb.firebaseapp.com',
    storageBucket: 'eaio-9e3cb.appspot.com',
    measurementId: 'G-PM77JEYLLF',
  );
}
